// логика переключения между View
export const VIEW_ID_START_WINDOW = "VIEW_ID_START_WINDOW";
export const VIEW_ID_LIST_AGE_AND_QUIZES = "VIEW_ID_LIST_AGE_AND_QUIZES";
export const VIEW_ID_LIST_QUESTIONES = "VIEW_ID_LIST_QUESTIONES";
export const VIEW_ID_RESULT = "VIEW_ID_RESULT";
export const VIEW_ID_ANSWERS_QUESTIONS = "VIEW_ID_ANSWERS_QUESTIONS";

export const VIEW_ID_SPINNER = "VIEW_ID_SPINNER";

