export const GO_TO_LIST_AGE = "VIEW_ID_START_WINDOW";
export const GO_TO_LIST_SURVEY = "VIEW_ID_START_WINDOW";

export const LIST_AGE_PANEL = "LIST_AGE_APNEL";
export const LIST_SURVEYS_PANEL = "LIST_SURVEYS_PANEL";