// export const SURVEY_FINISHED_GO_TO_RESULT_TRUE = "SURVEY_FINISHED_GO_TO_RESULT_TRUE"
// export const SURVEY_FINISHED_GO_TO_RESULT_FALSE = "SURVEY_FINISHED_GO_TO_RESULT_FALSE"
export const GIVE_ANSWER = "GIVE_ANSWER"
export const IS_NEED_DOWNLOAD_TRUE = "GIVE_ANSWER"